# Generated by Django 5.0 on 2024-03-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
