# Generated by Django 5.0 on 2024-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='studentId',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
