# Generated by Django 5.0 on 2024-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_course_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studentId',
            field=models.CharField(max_length=12),
        ),
    ]
