# Generated by Django 5.0 on 2024-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_course_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
