# Generated by Django 5.0 on 2024-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.CharField(default='F', max_length=12),
        ),
    ]
