# Generated by Django 5.0 on 2024-03-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_course_grade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course_table',
        ),
    ]
