# Generated by Django 5.0 on 2024-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_marks_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='studentId',
        ),
        migrations.AddField(
            model_name='marks',
            name='student_id',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grade_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='marks',
            table=None,
        ),
    ]
