# Generated by Django 5.0 on 2024-03-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_marks_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_id',
        ),
        migrations.AddField(
            model_name='marks',
            name='studentId',
            field=models.CharField(default='123', max_length=12),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grade',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='marks',
            name='grade_points',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='marks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='marks',
            table='Marks_table',
        ),
    ]
