# Generated by Django 5.0 on 2024-03-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_marks_student_id_marks_studentid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marks',
            table='Result_table',
        ),
    ]
