# Generated by Django 5.0 on 2024-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact',
            field=models.CharField(default='1234', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='studentId',
            field=models.CharField(default='123', max_length=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(default='1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
