# Generated by Django 5.0 on 2024-03-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_mark_studentid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentprofile',
            table='studentprofile_table',
        ),
    ]
