# Generated by Django 5.0 on 2024-03-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='student',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='payment_type',
            field=models.CharField(default=123, max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='studentId',
            field=models.CharField(default=123, max_length=20),
        ),
    ]
