# Generated by Django 5.0 on 2024-03-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_feepayment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_join', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employeeprofile_table',
            },
        ),
    ]
