# Generated by Django 4.2.5 on 2024-03-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='CorrectedbyfacultyName',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='Correctedbyfacultyid',
            field=models.CharField(default=1111, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(),
        ),
    ]
