# Generated by Django 4.2.5 on 2024-04-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
