# Generated by Django 4.2.5 on 2024-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='studentid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
